const route = {
  WELCOME: "WELCOME",
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  HOME: "HOME",
  CATEGORY: "CATEGORY",
  NOTIFICATION: "NOTIFICATION",
  CART: "CART",
  PROFILE: "PROFILE",
  FAVOURITE: "FAVOURITE",
} as const;

export default route;
