export default {
  left: require("../../assets/icons/left-arrow.png"),
  right: require("../../assets/icons/right-arrow.png"),
  home: require("../../assets/icons/house.png"),
  heart: require("../../assets/icons/love.png"),
  mail: require("../../assets/icons/mail.png"),
  order: require("../../assets/icons/order.png"),
  lock: require("../../assets/icons/padlock.png"),
  search: require("../../assets/icons/search.png"),
  cart: require("../../assets/icons/shopping-cart.png"),
  check: require("../../assets/icons/check-mark.png"),
  noti: require("../../assets/icons/notification.png"),
  electronics: require("../../assets/icons/responsive.png"),
  jewelery: require("../../assets/icons/jewellery.png"),
  men: require("../../assets/icons/clothes.png"),
  women: require("../../assets/icons/woman-clothes.png"),
  loading: require("../../assets/icons/loading.gif"),
};
